ptu5_library/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('author/<int:author_id>/', views.author, name='author'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book'),
    path('my_books/', views.UserBookListView.as_view(), name='user_books'),
]

ptu5_library/ptu5_library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_profile/', include('user_profile.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ptu5_library/library/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.html import format_html
from django.urls import reverse
from django.utils.timezone import datetime
from tinymce.models import HTMLField
import uuid


class Genre(models.Model):
    name = models.CharField('name', max_length=200, help_text='Enter name of book genre')

    def __str__(self) -> str:
        return self.name

    def link_filtered_books(self):
        link = reverse('books')+'?genre_id='+str(self.id)
        return format_html('<a class="genre" href="{link}">{name}</a>', link=link, name=self.name)


class Author(models.Model):
    first_name = models.CharField('first name', max_length=50)
    last_name = models.CharField('last name', max_length=50)
    
    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def display_books(self) -> str:
        return ', '.join(book.title for book in self.books.all())
    display_books.short_description = 'books'

    def link(self) -> str:
        link = reverse('author', kwargs={'author_id':self.id})
        return format_html('<a href="{link}">{author}</a>', link=link, author=self.__str__())

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = "author"
        verbose_name_plural = "authors"


class Book(models.Model):
    title = models.CharField('title', max_length=255)
    summary = HTMLField('summary')
    isbn = models.CharField('ISBN', max_length=13, null=True, blank=True, 
        help_text='<a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN code</a> consisting of 13 symbols')
    author = models.ForeignKey(
        Author, on_delete=models.SET_NULL, 
        null=True, blank=True, 
        related_name='books',
    )
    genre = models.ManyToManyField(Genre, help_text='Choose genre(s) for this book', verbose_name='genre(s)')
    cover = models.ImageField("cover", upload_to='covers', blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.author} - {self.title}"
    
    def display_genre(self) -> str:
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    display_genre.short_description = 'genre(s)'


class BookInstance(models.Model):
    unique_id = models.UUIDField('unique ID', default=uuid.uuid4, editable=False)
    book = models.ForeignKey(Book, verbose_name="book", on_delete=models.CASCADE)
    due_back = models.DateField('due back', null=True, blank=True)

    LOAN_STATUS = (
        ('m', "managed"),
        ('t', "taken"),
        ('a', "available"),
        ('r', "reserved"),
    )

    status = models.CharField('status', max_length=1, choices=LOAN_STATUS, default='m')
    reader = models.ForeignKey(
        get_user_model(), 
        verbose_name="reader", 
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='taken_books',
    )

    @property
    def is_overdue(self):
        if self.due_back and self.due_back < datetime.date(datetime.now()):
            return True
        return False

    def __str__(self) -> str:
        return f"{self.unique_id}: {self.book.title}"

    class Meta:
        ordering = ['due_back']


class BookReview(models.Model):
    book = models.ForeignKey(
        Book, 
        verbose_name="book", 
        on_delete=models.CASCADE, 
        related_name='reviews',
    )
    reader = models.ForeignKey(
        get_user_model(), 
        verbose_name="reader", 
        on_delete=models.CASCADE, 
        related_name='book_reviews',
    )
    created_at = models.DateTimeField("created at", auto_now_add=True)
    content = models.TextField("content", max_length=10000)

    def __str__(self):
        return f"{self.reader} on {self.book} at {self.created_at}"

    class Meta:
        ordering = ('-created_at', )

ptu5_library/library/forms.py
from django import forms
from django.utils.timezone import datetime, timedelta
from . models import BookReview

class BookReviewForm(forms.ModelForm):
    def is_valid(self) -> bool:
        valid = super().is_valid()
        if valid:
            reader = self.cleaned_data.get("reader")
            recent_posts = BookReview.objects.filter(
                reader=reader, 
                created_at__gte=(datetime.now()-timedelta(hours=1))
            )
            if recent_posts:
                return False
        return valid

    class Meta:
        model = BookReview
        fields = ('content', 'book', 'reader', )
        widgets = {
            'book': forms.HiddenInput(),
            'reader': forms.HiddenInput(),
        }

ptu5_library/library/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from . models import Genre, Author, Book, BookInstance
from . forms import BookReviewForm

# Create your views here.

def index(request):
    # return HttpResponse("Sveiki atvyke!")
    book_count = Book.objects.count()
    book_instance_count = BookInstance.objects.count()
    book_instance_available_count = BookInstance.objects.filter(status='a').count()
    author_count = Author.objects.count()
    visits_count = request.session.get('visits_count', 1)
    request.session['visits_count'] = visits_count + 1
    
    context = {
        'book_count': book_count,
        'book_instance_count': book_instance_count,
        'book_instance_available_count': book_instance_available_count,
        'author_count': author_count,
        'genre_count': Genre.objects.count(),
        'visits_count': visits_count,
    }

    return render(request, 'library/index.html', context)


def authors(request):
    paginator = Paginator(Author.objects.all(), 5)
    page_number = request.GET.get('page')
    paged_authors = paginator.get_page(page_number)
    return render(request, 'library/authors.html', {'authors': paged_authors })

def author(request, author_id):
    return render(request, 'library/author.html', {'author': get_object_or_404(Author, id=author_id)})


class BookListView(ListView):
    model = Book
    paginate_by = 5
    template_name = 'library/book_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(Q(title__icontains=search) | Q(summary__icontains=search))
        genre_id = self.request.GET.get('genre_id')
        if genre_id:
            queryset = queryset.filter(genre__id=genre_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['books_count'] = Book.objects.count()
        context['books_count'] = self.get_queryset().count()
        genre_id = self.request.GET.get('genre_id')
        context['genres'] = Genre.objects.all()
        if genre_id:
            context['genre'] = get_object_or_404(Genre, id=genre_id)
        return context


class BookDetailView(FormMixin, DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    form_class = BookReviewForm

    def get_success_url(self):
        return reverse('book', kwargs={'pk': self.get_object().id})

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            messages.error(self.request, "You're posting too much!")
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.book = self.get_object()
        form.instance.reader = self.request.user
        form.save()
        messages.success(self.request, 'Your review has been posted!')
        return super().form_valid(form)

    def get_initial(self):
        return {
            'book': self.get_object(),
            'reader': self.request.user,
        }


class UserBookListView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'library/user_book_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(reader=self.request.user).order_by('due_back')
        return queryset

ptu5_library/library/templates/library/author.html
{% extends 'library/base.html' %}
{% block title %}{{ author }} Books in {{ block.super }}{% endblock title %}
{% block content %}
    <h1>{{ author }} Books</h1>
    <ul>
        {% for book in author.books.all %}
            <li>{{ book }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

ptu5_library/library/templates/library/authors.html
{% extends 'library/base.html' %}
{% block title %}Authors in {{ block.super }}{% endblock title %}
{% block content %}
    <h1>Authors</h1>
    <div class="paginator">
        {% if authors.has_other_pages %}
            {% for page_number in authors.paginator.page_range %}
                {% if page_number == authors.number %}
                    <span>{{ page_number }}</span>
                {% else %}
                    <a href="?page={{ page_number }}">{{ page_number }}</a>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    <ul>
        {% for author in authors %}
            <li><a href="{% url 'author' author.id %}">{{ author.last_name }}, {{ author.first_name }}</a></li>
        {% endfor %}
    </ul>
    {# authors #}
{% endblock content %}

ptu5_library/library/templates/library/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Library{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'library/css/base.css' %}">
</head>
<body>
    <header>
        {% comment %} meniukas {% endcomment %}
        <div class="container">
            {% block nav %}
                <a href="{% url 'index' %}">Home</a>
                <a href="{% url 'authors' %}">Authors</a>
                <a href="{% url 'books' %}">Books</a>
                <span class="spacer"></span>
                {% if user.is_authenticated %}
                    <span>{{ user }}</span>
                    <a href="{% url 'user_books' %}">My Books</a>
                    {% if user.is_superuser or user.is_staff %}
                        <a href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'register' %}">Register</a>
                    <a href="{% url 'login' %}{% if not '/accounts/' in request.path %}?next={{ request.path }}{% endif %}">Login</a>
                {% endif %}
            {% endblock nav %}
        </div>
    </header>
    <main>
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <footer>
        <div class="container">
            {% block footer %}<p>(C) 2022 PTU5</p>{% endblock footer %}
        </div>
    </footer>
</body>
</html>

ptu5_library/library/templates/library/book_detail.html
{% extends 'library/base.html' %}
{% block title %}{{ object }}{% endblock title %}
{% block content %}
    <h1>{{ object.title }}</h1>
    <h3>by {{ object.author.link }}</h3>
    {% if object.isbn %}
        <p>ISBN: {{ object.isbn }}</p>
    {% endif %}
    {% if object.genre %}
        <p>Genres: {# object.genre.all|join:", " #}
            {% for genre in object.genre.all %}
                {{ genre.link_filtered_books }}
            {% endfor %}
        </p>
    {% endif %}
    <div class="summary">
        {{ object.summary|safe }}
    </div>
    <h2>Reviews</h2>
    {% if user.is_authenticated %}
        <div class="review-form">
            <p>If you have read this book, please leave a review.</p>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p><button type="submit">Post Review</button></p>
            </form>
        </div>
    {% endif %}
    {% if book.reviews %}
        {% for review in book.reviews.all %}
            <div class="book-review">
                <h4>{{ review.reader }}
                    <span class="float-right">{{ review.created_at }}</span></h4>
                <p>{{ review.content }}</p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

ptu5_library/library/templates/library/book_list.html
{% extends 'library/base.html' %}
{% load static %}
{% block title %}Books in {{ block.super }}{% endblock title %}
{% block content %}
    <h1>{{ books_count }} 
        {% if genre %}{{ genre }}{% endif %}
        Books</h1>
    <div class="paginator">
        {% if page_obj.has_previous %}
            <a href="?{% if request.GET.search %}search={{ request.GET.search }}&{% endif %}page=1">&#11120;</a>
            <a href="?{% if request.GET.search %}search={{ request.GET.search }}&{% endif %}page={{ page_obj.previous_page_number }}">&#129120;</a>
        {% endif %}
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?{% if request.GET.search %}search={{ request.GET.search }}&{% endif %}page={{ page_obj.next_page_number }}">&#129122;</a>
            <a href="?{% if request.GET.search %}search={{ request.GET.search }}&{% endif %}page={{ page_obj.paginator.num_pages }}">&#11122;</a>
        {% endif %}
        <form action="{% url 'books' %}" method="get">
            <input type="text" name="search" value="{{ request.GET.search }}">
            <button type="submit">search</button>
        </form>
    </div>
    <div class="genre_filter">
        <h3>Available Genres</h3>
        <ul>
            {% for filter_genre in genres %}
                <li class="{% if filter_genre == genre %}current{% endif %}">{{ filter_genre.link_filtered_books }}</li>
            {% endfor %}
        </ul>
    </div>
    <ul class="book_list">
        {% for book in book_list %}
            <li class="book">
                <a href="{% url 'book' book.pk %}">
                    {% if book.cover %}
                        <img src="{{ book.cover.url }}">
                    {% else %}
                        <img src="{% static 'library/img/news3-1.jpg' %}">
                    {% endif %}
                    <h3>{{ book.title }}</h3>
                </a>
                <p>by {{ book.author.link }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

ptu5_library/library/templates/library/index.html
{% extends 'library/base.html' %}
{% block title %}Welcome to {{ block.super }}{% endblock title %}
{% block content %}
<h1>PTU5 Library</h1>
<ul>
    <li>Total books: {{ book_count }}</li>
    <li>Total book copies: {{ book_instance_count }}</li>
    <li>Available book copies: {{ book_instance_available_count }}</li>
    <li>Distinct authors: {{ author_count }}</li>
    <li>Genres: {{ genre_count }}</li>
    <li>Visits this session: {{ visits_count }}</li>
</ul>
{% endblock content %}

ptu5_library/library/templates/library/user_book_list.html
{% extends 'library/base.html' %}
{% block title %}My Books in {{ block.super }}{% endblock title %}
{% block content %}
<h1>My Books</h1>
<div class="table-grid my-books-table">
    <div class="table-grid-cell center dark">Author - Book</div>
    <div class="table-grid-cell center dark">Due Date</div>
    <div class="table-grid-cell center dark">Status</div>
    {% for book_instance in bookinstance_list %}
        <div class="table-grid-cell">{{ book_instance.book }}</div>
        <div class="table-grid-cell center{% if book_instance.is_overdue %} overdue{% endif %}">{{ book_instance.due_back }}</div>
        <div class="table-grid-cell center{% if book_instance.is_overdue %} overdue{% endif %}">{{ book_instance.get_status_display }}</div>
    {% endfor %}
</div>
{% endblock content %}